<a href="https://colab.research.google.com/github/FilipeSacchetto/Python-Machine-Learning-for-Begginers/blob/master/Aprendizado_de_Maquinas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Pré-processamento de dados ####

##### Leitura dos dados #####

In [0]:
#importando as bibliotecas
import pandas as pd
import numpy as np

In [4]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
dataset = pd.read_csv("https://pycourse.s3.amazonaws.com/Data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [6]:
dataset.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [0]:
X, y = dataset.drop(['Purchased'], axis = 1), dataset["Purchased"]

In [8]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [9]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

##### Alternativa #####

In [0]:
column_names = dataset.columns.values
X = dataset.loc[:, column_names[:-1]]
y = dataset.loc[:, column_names[-1]]
print(X)
print(y)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0
0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size = 0.2, random_state = 0, stratify = y)

In [12]:
print(X_train[:3, :])

[['France' 44.0 72000.0]
 ['Germany' 40.0 nan]
 ['Spain' nan 52000.0]]


In [0]:
#tratamento de dados faltantes
from sklearn.impute import SimpleImputer

In [0]:
# substituindo NaN pela média
imputer = SimpleImputer(strategy = 'mean')

In [0]:
# fit X_train
imputer = imputer.fit(X_train[:,1:3])

In [0]:
# aplicando a transformação no dataset de treinamento
X_train[:,1:3] = imputer.transform(X_train[:, 1:3])

# aplicando a transformação no dataset de test
X_test[:,1:3] = imputer.transform(X_test[:, 1:3])

In [18]:
print(X_train)
print(X_test)

[['France' 44.0 72000.0]
 ['Germany' 40.0 58857.142857142855]
 ['Spain' 35.857142857142854 52000.0]
 ['France' 37.0 67000.0]
 ['Spain' 38.0 61000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['France' 35.0 58000.0]]
[['Germany' 50.0 83000.0]
 ['France' 48.0 79000.0]]


In [0]:
# média sensivel a outlier 
# mediana não

In [0]:
#codificando a variável categorica presente em X 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [0]:
# instanciando objetivo ColumnTransformer

ct_X = ColumnTransformer(transformers=[('onehot',
                                        OneHotEncoder(),
                                        [0])],
                         remainder='passthrough')

In [0]:
# aplicando a transformação em X_train
X_train = ct_X.fit_transform(X_train)

# aplicando a transformação em X_test
X_test = ct_X.transform(X_test)

In [31]:
print('X_train:', X_train)
print('\n','X_test:', X_test) 

X_train: [[1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 40.0 58857.142857142855]
 [0.0 0.0 1.0 35.857142857142854 52000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 35.0 58000.0]]

 X_test: [[0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 48.0 79000.0]]


In [0]:
# valores categoricos podem ser representados por n-1 caso as colunas fechem a lógica de exclusão
X_train = X_train[: , 1:]
X_test = X_test[: , 1:]


# basei o corte das categorias por pvalor

In [37]:
print('X_train: \n', X_train)
print('\n','X_test: \n', X_test) 

X_train: 
 [[0.0 0.0 44.0 72000.0]
 [1.0 0.0 40.0 58857.142857142855]
 [0.0 1.0 35.857142857142854 52000.0]
 [0.0 0.0 37.0 67000.0]
 [0.0 1.0 38.0 61000.0]
 [0.0 1.0 27.0 48000.0]
 [1.0 0.0 30.0 54000.0]
 [0.0 0.0 35.0 58000.0]]

 X_test: 
 [[1.0 0.0 50.0 83000.0]
 [0.0 0.0 48.0 79000.0]]


In [0]:
# codificando a variavel dependente y
from sklearn.preprocessing import LabelEncoder


In [0]:
# aplicando o LabelEncoder
labelencoder_y = LabelEncoder()
y_train = labelencoder_y.fit_transform(y_train)
y_test = labelencoder_y.transform(y_test) 

In [41]:
y_train

array([0, 1, 0, 1, 0, 1, 0, 1])

## Escalando dados Numéricos ##

In [0]:
from sklearn.preprocessing import StandardScaler

# instanciando o StandardScaler e normalizando os dados
# é possível fazer tudo dentro do ColumnTransformer
sc_X = StandardScaler()
X_train[:, 2:] = sc_X.fit_transform(X_train[:, 2:])
X_test[:, 2:] = sc_X.transform(X_test[:, 2:])

In [43]:
print('X_train: \n', X_train)
print('\n','X_test: \n', X_test) 

X_train: 
 [[0.0 0.0 1.6170619456335291 1.786744634382875]
 [1.0 0.0 0.8227157267258302 0.0]
 [0.0 1.0 -1.4110423388084194e-15 -0.9322145918519343]
 [0.0 0.0 0.22695606254505601 1.1070048278241726]
 [0.0 1.0 0.4255426172719807 0.29131705995372986]
 [0.0 1.0 -1.758909484724191 -1.4760064370988963]
 [1.0 0.0 -1.163149820543417 -0.6603186692284534]
 [0.0 0.0 -0.1702170469087934 -0.11652682398149154]]

 X_test: 
 [[1.0 0.0 2.8085812739950775 3.28217220881202]
 [0.0 0.0 2.411408164541228 2.7383803635650583]]


[Perguntas](https://drive.google.com/file/d/1K2DpqvVWsJqLoPt7R0Ipx9lCJZNjRnj3/view?usp=sharing)

1.   Caso tenha uma coluna ordenada alfabeticamente por exemplo, caso não embaralhe os dados, você pode enviezar seu modelo.

2.   *random_state* -> é um randonizador numérico, normalmente coloca-se um valor qualquer para regular e igualizar o número de randonizações, assim sempre que for fazer um novo fit no seu treino o valor será o mesmo.
      
      *stratify* -> controla a proporção de dados no momento do split, assim você não terá apenas 0's no seu treino e 1's no seu test

3.  

